# Generated by Django 5.2.17 on 2026-09-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_firebase_uid_alter_appuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='language',
            field=models.CharField(default='fr', max_length=5),
        ),
    ]
