# Generated by Django 4.2.13 on 2026-07-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('images', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('available_spots', models.IntegerField(default=50)),
                ('discount', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-rating'],
            },
        ),
    ]
