# Generated by Django 5.2.17 on 2026-09-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
